import '../widget.css'
import './spotify-obsessions.css'

import { useSearchParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { stringify } from 'querystring';
import fetchSpotifyData, { type AccessData, CLIENT_ID, REDIRECT_URI } from './fetch-data'
import writeToPlaylist from './write-data';
import ListTrack from './list-track';

const SCOPE = 'user-top-read user-read-private user-read-email playlist-modify-public';
const max_selectable_items = 10;

export type Artist = {
    name: string
}

export type Track = {
    uri: string,
    name: string,
    artists: Artist[]
}

export function SpotifyObsessions() {
    const [code, setCode] = useState("");
    const [access_data, setAccessData] = useState<AccessData | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const [get_vals] = useSearchParams();

    const [tracks, setTracks] = useState<Track[]>([]);
    const [selected, setSelected] = useState<Track[]>([]);

    // user auth
    const auth_link = `https://accounts.spotify.com/authorize?` + stringify({
        response_type: "code",
        client_id: CLIENT_ID,
        scope: SCOPE,
        redirect_uri: REDIRECT_URI
    });

    useEffect(() => {
        const hash = get_vals.get("code");
        let cd = window.localStorage.getItem("code");

        if (!cd && hash) {
            cd = hash;
            window.localStorage.setItem("code", cd);
        }
        setCode(cd ?? ''); // save the code that is in the return url
    }, []);

    const logout = () => {
        setCode("");
        window.localStorage.removeItem("code");
    }

    // button onclick function
    const fetch = async () => {
        setError("");
        setLoading(true);
        const endpoint = "me/top/tracks?limit=50&time_range=short_term";
        const result = await fetchSpotifyData(code, access_data, endpoint);
        if (result){
            console.log(result[1]);
            if (result[0]) setAccessData(result[0]);
            if (result[1]) setTracks(result[1]["items"]);
        }
        else {
            setError("Spotify session ended!");
            logout();
        }
        setLoading(false);
    }

    const trackChecked = (event : React.ChangeEvent<HTMLInputElement>) => {
        const entry: Track = {
            uri: `${event.target.id}`,
            name: `${event.target.value}`,
            artists: []
        }
        if (event.target.checked) {
            // add an item to the selected list
            setSelected([...selected, entry]);
        }
        else {
            // remove an item from the selected list
            setSelected(selected => selected.filter(item => item.uri !== entry.uri));
        }
    }

    const exportObsessions = async () => {
        console.log("Under construction");
        await writeToPlaylist(code, access_data);
    }
/*
<div className='playlistEntry'>
    <label htmlFor='playlist_name'>Playlist Name: </label>
    <input id='playlist_name' type='text' onChange={e => setPlaylistName(e.target.value)}></input>
    <p className='warning'>don't choose a name of an existing playlist if it was not generated by this page</p>
</div>
*/
    return (<div className='widget obsessions'>
        <h2>Obsessions</h2>
        {!code ?
            <a href={auth_link}>Login to Spotify</a>
            : <div>
                <button name="fetch" onClick={fetch}>Fetch</button>
                <button className="logout" onClick={logout}>Logout</button>
            </div>}
        {loading ? <p>Loading...</p> : <div></div>}
        <p>{error} </p>
        <div className="data">
            <div className='top'>
                <div className='listheader'>
                    <h4 className='listtitle'>Your top tracks recently:</h4>
                </div>
                <ul className='trackList'>
                    {tracks && code ? tracks.map((track: Track) => (
                        <li key={track.uri} className='track'>
                            <ListTrack track={track} onCheckChanged={() => trackChecked} isFull={selected.length >= max_selectable_items}></ListTrack>
                        </li>
                    )) : ""}
                </ul>
            </div>
            <div className="selected">
                <div className='listheader'>
                    <h4 className='listtitle'>Selected tracks: {selected.length} </h4>
                    {code ? <button className='export' onClick={exportObsessions}>Export</button> : ""}
                </div>
                <ul className='trackList playlist'>
                    {selected && tracks && code ? selected.map((track: Track) => (
                        <li key={track.uri} className='track'>
                            <p className="trackName">
                                {track.name}
                            </p>
                        </li>
                    )) : ""}
                </ul>
            </div>
        </div>
    </div>)
}